# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    groups:
      material:
        patterns:
          - "@mui*"
      jest:
        patterns:
          - "*jest*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    groups:
      gorm:
        patterns:
        - "gorm.io*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
