name: daily
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  check_outdated_yarn_deps:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: 16.17.1

      - name: Yarn Outdated
        run: yarn outdated