name: test

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Set up Yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: 18.14.2

      - name: Yarn Test

        run: yarn test

      - name: Yarn Build
        run: yarn build

      - name: Build Go
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
