name: test

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'v1.21.6'

      - name: Set up Yarn
        uses: mskelton/setup-yarn@v2
        with:
          node-version: 18.14.2

      - name: Yarn Test

        run: yarn test

      - name: Yarn Build
        run: yarn build

      - name: Build Go
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
