name: test

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: 16.17.1
        run: yarn build

      - name: Build Go
        run: go build -v ./...

      - name: Test
        run: go test -v ./...