name: test

on:
  schedule:
    - cron: "15 4,5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Yarn
        uses: mskelton/setup-yarn@v2
        with:
          node-version: 22.2.0

      - name: bump
        run: npx update-browserslist-db@latest

      - name: Yarn Build
        run: yarn build

      - name: Build Go
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
